create table wiki_user
(
    DATA_ID            VARCHAR(32),
    DATA_DATE          VARCHAR(8),
    DATA_DATE_TIME     VARCHAR(14),
    crt_user           VARCHAR(32),
    crt_date           VARCHAR(8),
    crt_time           VARCHAR(14),
    chg_user           VARCHAR(32),
    chg_date           VARCHAR(8),
    chg_time           VARCHAR(14),
    apv_user           VARCHAR(32),
    apv_date           VARCHAR(8),
    apv_time           VARCHAR(14),
    remarks            VARCHAR(2000),
    user_id            VARCHAR(64),
    user_name          VARCHAR(128),
    password           VARCHAR(512),
    role_id            VARCHAR(64),
    login_ip           VARCHAR(128),
    status             CHAR(1),
    is_lock            CHAR(1),
    last_access_time   VARCHAR(14),
    last_logout_time   VARCHAR(14),
    last_fail_time     VARCHAR(14),
    pswd_err_cnt       VARCHAR(2),
    tot_pswd_err       VARCHAR(4),
    last_chg_pswd_time VARCHAR(14),
    rsv1               VARCHAR(128),
    rsv2               VARCHAR(128),
    rsv3               VARCHAR(128),
    rsv4               VARCHAR(128),
    rsv5               VARCHAR(128),
    access_token_id    VARCHAR(512)
);